'use client';
import {useState,useEffect} from 'react';
import {api,post} from '../lib/api';
export default function Admin({notify}:{notify:(s:string)=>void}){
 const [directory,setDirectory]=useState<any>(null),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState('victim'),[district,setDistrict]=useState('D1'),[state,setState]=useState('S1'),[victim,setVictim]=useState(''),[busy,setBusy]=useState(false);
 const refresh=()=>api('/directory').then(setDirectory).catch(e=>notify(e.message));
 useEffect(()=>{refresh();},[]);
 async function action(fn:()=>Promise<void>){setBusy(true);try{await fn();await refresh();notify('Saved successfully');}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
 if(!directory)return <section className="card">Loading directory…</section>;
 const districts=<label>District<select value={district} onChange={e=>{setDistrict(e.target.value);setState(directory.districts.find((d:any)=>d.id===e.target.value).state_id);}}>{directory.districts.map((d:any)=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label>;
 return <><div className="page-heading"><div><p className="eyebrow">SYSTEM ADMINISTRATION</p><h1>Users & case onboarding</h1><p>Provision synthetic participants and authorized staff.</p></div></div><div className="two-col"><section className="card"><h2>Create user</h2><form onSubmit={e=>{e.preventDefault();action(async()=>{const created=await post('/auth/register',{name,email,password,role,district_id:district,state_id:state});setName('');setEmail('');setPassword('');if(created.victim_id)setVictim(created.victim_id);});}}><label>Display name<input value={name} onChange={e=>setName(e.target.value)} required maxLength={100}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Initial password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={10} autoComplete="new-password"/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}>{['victim','counsellor','officer','state','national','admin'].map(v=><option key={v}>{v}</option>)}</select></label>{districts}<label>State<select value={state} onChange={e=>setState(e.target.value)}>{directory.states.map((s:any)=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><button disabled={busy}>Create user</button></form></section><section className="card"><h2>Open case for participant</h2><form onSubmit={e=>{e.preventDefault();action(async()=>{await post('/cases',{victim_id:victim,district_id:district,case_type:'Complainant'});setVictim('');});}}><label>Participant without a case<select required value={victim} onChange={e=>setVictim(e.target.value)}><option value="">Select participant</option>{directory.unlinked_victims.map((v:any)=><option key={v.id} value={v.id}>{v.alias} · {v.id}</option>)}</select></label>{districts}<button disabled={busy||!victim}>Create case</button></form><p className="muted">A newly created participant signs in with their assigned credentials, gives consent, and starts their own support journey.</p></section></div><section className="card"><h2>User directory</h2><div className="table-scroll"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>District</th></tr></thead><tbody>{directory.users.map((u:any)=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.role}</td><td>{u.district_id}</td></tr>)}</tbody></table></div></section></>;
}
