'use client';
import {useEffect,useState} from 'react';
import dynamic from 'next/dynamic';
import {ArrowUpRight,Search,RefreshCw,Activity} from 'lucide-react';
import {api,post,patch,date,User} from '../lib/api';
import type {CaseSummary, ResearchPayload} from '../lib/types';
import {Trend,Bars} from './Charts';
import CaseDetail,{Badge} from './CaseDetail';
const DistrictMap=dynamic(()=>import('./DistrictMap'),{ssr:false});
export default function Authority({user,view,notify}:{user:User;view:string;notify:(s:string)=>void}){
 const [dashboard,setDashboard]=useState<any>(null),[cases,setCases]=useState<CaseSummary[]>([]),[alerts,setAlerts]=useState<any[]>([]),[followups,setFollowups]=useState<any[]>([]),[research,setResearch]=useState<ResearchPayload|null>(null),[audit,setAudit]=useState<any[]>([]),[selected,setSelected]=useState<string|null>(null),[search,setSearch]=useState(''),[risk,setRisk]=useState(''),[district,setDistrict]=useState(''),[trend,setTrend]=useState(''),[threat,setThreat]=useState(false),[loading,setLoading]=useState(false),[filterDate,setFilterDate]=useState(''),[type,setType]=useState(''),[assignee,setAssignee]=useState('');
 const aggregate=['state','national'].includes(user.role);
 const level=user.role==='state'?'state':user.role==='national'?'national':'district';
 async function refresh(){setLoading(true);try{
   setDashboard(await api('/dashboard/'+level));
   if(!aggregate){const [c,a,f]=await Promise.all([api<CaseSummary[]>('/cases'),api('/alerts'),api('/follow-ups')]);setCases(c);setAlerts(a as any[]);setFollowups(f as any[]);}
   if(user.role==='admin'){setResearch(await api<ResearchPayload>('/research'));setAudit(await api('/audit-logs'));}
 }catch(e){notify((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,30000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{setSelected(null);},[view]);
 if(selected)return <CaseDetail id={selected} onBack={()=>{setSelected(null);refresh();}} notify={notify}/>;
 const filtered=cases.filter(c=>(!search||String(c.id??'').toLowerCase().includes(search.toLowerCase()))&&(!risk||c.priority===risk)&&(!district||c.district===district)&&(!trend||c.trend?.direction===trend)&&(!threat||c.conditions?.threat||(c.scores?.safety_risk??0)>=55)&&(!filterDate||(typeof c.last_checkin==='string'&&c.last_checkin.slice(0,10)>=filterDate))&&(!type||c.case_type===type)&&(!assignee||c.assigned_to===assignee));
 const queue=<section className="card"><div className="section-heading"><div><h2>Priority case queue</h2><p className="muted">Prioritized by the highest distress, safety, or escalation indicator.</p></div><span className="badge">{filtered.length} cases</span></div><div className="filters"><label className="search"><Search size={17}/><input placeholder="Search case ID" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Risk filter" value={risk} onChange={e=>setRisk(e.target.value)}><option value="">All risk levels</option>{['Critical','High','Moderate','Mild','Low'].map(s=><option key={s}>{s}</option>)}</select><select aria-label="District filter" value={district} onChange={e=>setDistrict(e.target.value)}><option value="">All districts</option>{Array.from(new Set(cases.map(c=>c.district).filter(Boolean) as string[])).map(s=><option key={s}>{s}</option>)}</select><select aria-label="Trend filter" value={trend} onChange={e=>setTrend(e.target.value)}><option value="">All trends</option>{['Improving','Stable','Worsening'].map(s=><option key={s}>{s}</option>)}</select></div><details><summary>More filters</summary><div className="filters"><label>Since<input type="date" value={filterDate} onChange={e=>setFilterDate(e.target.value)}/></label><label>Case type<select value={type} onChange={e=>setType(e.target.value)}><option value="">All</option><option>Complainant</option><option>Witness</option></select></label><label>Assigned person<select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">All</option>{Array.from(new Set(cases.map(c=>c.assigned_to).filter(Boolean) as string[])).map(s=><option key={s}>{s}</option>)}</select></label><label className="check"><input type="checkbox" checked={threat} onChange={e=>setThreat(e.target.checked)}/>Threat / safety signal</label></div></details>
 <div className="table-scroll"><table><thead><tr><th>Case ID</th><th>District / stage</th><th>Priority</th><th>Distress</th><th>Safety</th><th>Escalation</th><th>Trajectory</th><th>Last check-in</th><th>Review</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><strong>{c.id}</strong></td><td>{c.district}<small>{c.stage}</small></td><td><Badge value={c.priority||'Unassessed'}/></td><td>{c.scores?.distress??'—'}</td><td>{c.scores?.safety_risk??'—'}</td><td>{c.scores?.escalation_risk??'—'}</td><td><Badge value={c.trend?.direction||'Unknown'}/></td><td><small>{c.last_checkin?date(c.last_checkin):'—'}</small></td><td><button aria-label={'Review '+c.id} className="icon-button" onClick={()=>setSelected(c.id)}><ArrowUpRight size={18}/></button></td></tr>)}</tbody></table>{!filtered.length&&<p className="empty">No cases match these filters.</p>}</div></section>;
 if(view==='research')return <><div className="page-heading"><div><p className="eyebrow">MODEL GOVERNANCE</p><h1>Research & model monitoring</h1><p>Prototype model — not clinically validated.</p></div></div>{research&&<><section className="card"><h2>{research.metrics.version||'Rule-based baseline'}</h2><p className="notice">{research.metrics_framing||'Synthetic holdout metrics only — not field or clinical performance.'}</p><p>{research.metrics.split}</p><p>{research.metrics.limitations||research.limitation}</p><div className="kpi-grid">{['accuracy','precision','recall','f1','roc_auc'].map(k=><div className="kpi" key={k}><span>{k.toUpperCase()} <small>(synthetic)</small></span><strong>{research.metrics[k]===undefined?'N/A':(research.metrics[k]*100).toFixed(1)+'%'}</strong></div>)}</div><p>Training: {research.metrics.training_date} · Dataset: {research.metrics.dataset_version} · {research.metrics.records} records</p></section><div className="two-col"><section className="card"><h2>Feature importance (absolute coefficients)</h2><Bars data={research.metrics.feature_importance||[]}/></section><section className="card"><h2>Confusion matrix</h2><pre>{JSON.stringify(research.metrics.confusion_matrix,null,2)}</pre><p>Rows: actual [no escalation, escalation]. Columns: predicted.</p><h3>Fallback usage: {research.fallback_usage}</h3><pre>{JSON.stringify(research.prediction_distribution,null,2)}</pre></section></div><section className="card"><h2>Bias evaluation limitations</h2>{Object.entries(research.bias_evaluation||{}).map(([k,v])=><div className="list-row" key={k}><strong>{k}</strong><span>{String(v)}</span></div>)}</section></>}</>;
 if(view==='audit')return <section className="card"><h1>Access & action audit</h1><div className="table-scroll"><table><thead><tr><th>When</th><th>User</th><th>Action</th><th>Resource</th></tr></thead><tbody>{audit.map(a=><tr key={a.id}><td>{date(a.created_at)}</td><td>{a.user_id}</td><td>{a.action}</td><td>{a.resource}</td></tr>)}</tbody></table></div></section>;
 if(view==='alerts')return <><div className="page-heading"><div><p className="eyebrow">HUMAN REVIEW</p><h1>Alerts & escalation</h1><p>Every alert carries evidence and a recommended next step.</p></div><button className="secondary" onClick={refresh}><RefreshCw size={16}/> Refresh</button></div><section className="card">{alerts.map(a=><div className="alert-row" key={a.id}><div><div className="button-row"><strong>{a.case_id}</strong><Badge value={a.data.priority}/><span className="muted">{date(a.created_at)}</span></div><p>{a.data.trigger?.map((t:any)=>t.factor).join(' · ')||'Elevated wellbeing indicators'}</p><small>{a.data.recommendations?.join(' · ')}</small><details><summary>Evidence</summary><pre>{JSON.stringify(a.data.explanation,null,2)}</pre></details></div><div className="button-row"><select aria-label={'Alert status '+a.id} value={a.status} onChange={async e=>{try{await patch('/alerts/'+a.id,{status:e.target.value});refresh();}catch(err){notify((err as Error).message);}}}>{['New','Acknowledged','Assigned','In Progress','Resolved','Closed'].map(s=><option key={s}>{s}</option>)}</select><button className="secondary" onClick={()=>setSelected(a.case_id)}>Review case</button></div></div>)}{!alerts.length&&<p className="empty">No alerts in your assigned scope.</p>}</section></>;
 if(view==='followups')return <section className="card"><h1>Follow-up schedule</h1>{followups.map(f=><div className="list-row" key={f.id}><div><strong>{f.case_id}</strong><small>{date(f.due_at)}</small></div><Badge value={f.status}/><button className="secondary" onClick={()=>setSelected(f.case_id)}>Record contact</button></div>)}</section>;
 return <><div className="page-heading"><div><p className="eyebrow">{level.toUpperCase()} WELLBEING INTELLIGENCE</p><h1>{view==='cases'?'Case registry':'A clearer view. Earlier support.'}</h1><p>{aggregate?'Aggregate oversight across your authorized region.':'Monitor change, prioritize concerns, and connect people to support.'}</p></div><button className="secondary" onClick={refresh} disabled={loading}><RefreshCw size={16}/> {loading?'Updating…':'Refresh'}</button></div>
 {view!=='cases'&&dashboard&&<><div className="kpi-grid">{Object.entries(dashboard.kpis).map(([k,v],i)=><section className="card kpi" key={k}><div className="kpi-label"><span>{k}</span><Activity size={17}/></div><strong className={i===2?'critical-text':''}>{String(v)}</strong><small>Current authorized scope</small></section>)}</div><div className="two-col wide-left"><section className="card"><div className="section-heading"><div><h2>Wellbeing trends</h2><p className="muted">Average distress indicators over time</p></div><span className="badge">Longitudinal view</span></div><Trend data={dashboard.trend}/></section><section className="card"><h2>Risk distribution</h2><p className="muted">Highest of the three risk dimensions</p><Bars data={dashboard.risk_distribution}/></section></div></>}
 {!aggregate&&queue}
 {view!=='cases'&&dashboard&&<><div className="two-col"><section className="card"><h2>District risk density</h2><p className="muted">Synthetic geographic counts · select a marker</p><DistrictMap districts={dashboard.districts}/></section><section className="card"><h2>Regional overview</h2>{dashboard.districts.map((d:any)=><div className="list-row" key={d.name}><div><strong>{d.name}</strong><small>{d.state}</small></div><span>{d.count} cases</span><Badge value={d.high+' high / critical'}/></div>)}<p className="muted">Response time: {dashboard.response_time_note}</p></section></div><div className="three-col"><section className="card"><h2>Intervention status</h2><Bars data={dashboard.intervention_status}/></section><section className="card"><h2>Observed trajectories</h2><Bars data={dashboard.trajectories}/></section><section className="card"><h2>Case stages</h2><Bars data={dashboard.case_stages}/></section></div></>}
 </>;
}
