'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,TrendingUp,ShieldCheck} from 'lucide-react';
import {api,post,patch,date} from '../lib/api';
import {Trend} from './Charts';
export function Badge({value}:{value:string}){return <span className={'badge '+value.toLowerCase().replaceAll(' ','-')}>{value}</span>;}
export default function CaseDetail({id,onBack,notify}:{id:string;onBack:()=>void;notify:(v:string)=>void}){
 const [item,setItem]=useState<any>(null),[staff,setStaff]=useState<any[]>([]),[assigned,setAssigned]=useState(''),[kind,setKind]=useState('Counsellor follow-up'),[notes,setNotes]=useState(''),[due,setDue]=useState(''),[busy,setBusy]=useState(false),[event,setEvent]=useState(''),[eventKind,setEventKind]=useState('general'),[outcome,setOutcome]=useState('');
 async function refresh(){setItem(await api('/cases/'+id));}
 useEffect(()=>{Promise.all([refresh(),api('/staff').then(s=>{setStaff(s);setAssigned(s.find((u:any)=>u.role==='counsellor')?.id||s[0]?.id||'');})]).catch(e=>notify(e.message));},[id]);
 async function act(fn:()=>Promise<void>){setBusy(true);try{await fn();await refresh();notify('Saved successfully');}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
 if(!item)return <div className="card">Loading case…</div>;
 const latest=item.latest;
 return <><button className="text-button" onClick={onBack}><ArrowLeft size={16}/> Back to queue</button><div className="page-heading"><div><p className="eyebrow">CASE WELLBEING PROFILE · {item.district}</p><h1>{item.id}</h1><p>{item.stage} · Longitudinal support record</p></div><Badge value={item.priority}/></div>
 {latest&&<><div className="kpi-grid three">{Object.entries(latest.scores).map(([k,v])=><section className="card kpi" key={k}><span>{k.replaceAll('_',' ')}</span><strong>{String(v)}<small>/100</small></strong><p>{k==='escalation_risk'?latest.prediction.method:'Prototype indicator'}</p></section>)}</div>
 <div className="two-col"><section className="card change-panel"><p className="eyebrow">EARLY WARNING INTELLIGENCE</p><h2>What changed?</h2>{latest.what_changed.map((c:any,i:number)=><div className="change" key={i}><TrendingUp size={17}/><div>{c.factor}<small>{c.source}</small></div></div>)}<div className="notice">{latest.trend.direction} · {latest.trend.rapid_escalation?'Rapid escalation detected':'Trajectory under observation'}</div></section>
 <section className="card"><div className="section-heading"><h2>Wellbeing over time</h2><Badge value={latest.trend.direction}/></div><Trend data={item.history.map((h:any)=>({date:h.at,distress:h.score}))}/><div className="button-row">{[7,14,30].map(n=><span className="badge" key={n}>{n}d: {latest.trend['change_'+n+'d']??'Insufficient history'}</span>)}</div><p className="muted">Case events below show temporal context, not proof of causation.</p></section></div>
 <div className="two-col"><section className="card"><h2>Why this estimate?</h2><p className="muted">Contributions to distress score. Available inputs are reweighted; rounded total: {latest.scores.distress}.</p>{latest.explanation.map((e:any,i:number)=><div className="explanation" key={i}><div><span>{e.factor}</span><small>{e.source}</small></div><div className="bar-track"><i style={{width:Math.min(100,e.impact*3)+'%'}}/></div><strong>+{e.impact}</strong></div>)}<p className="muted">Missing inputs: {latest.missing_inputs.join(', ')||'none'}. {latest.limitations}</p><details><summary>NLP evidence and voice baseline</summary><pre>{JSON.stringify({sentiment:latest.sentiment,emotions:latest.emotions,evidence:latest.evidence,voice:latest.voice,baseline:latest.baseline},null,2)}</pre></details></section>
 <section className="card"><h2><ShieldCheck size={18}/> Recommended human support</h2>{latest.recommendations.map((r:string)=><div className="list-row" key={r}>{r}</div>)}<p className="muted">Recommendations do not authorize action. Confirm an assignment below.</p><form onSubmit={e=>{e.preventDefault();act(async()=>{await post('/interventions',{case_id:id,kind,assigned_to:assigned,notes});setNotes('');});}}><label>Intervention<select value={kind} onChange={e=>setKind(e.target.value)}>{['Counsellor follow-up','Safety/protection review','Legal support review','Financial assistance review','Rehabilitation support review','Urgent human assessment'].map(k=><option key={k}>{k}</option>)}</select></label><label>Assign to<select value={assigned} onChange={e=>setAssigned(e.target.value)}>{staff.map(s=><option key={s.id} value={s.id}>{s.name} · {s.role}</option>)}</select></label><label>Internal notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={3000}/></label><button disabled={busy||!assigned}>Confirm intervention</button></form></section></div></>}
 <div className="two-col"><section className="card"><h2>Case event timeline</h2>{item.events.map((e:any)=><div className="timeline-item" key={e.id}><span className="timeline-dot"/><div><strong>{e.data.title}</strong><small>{date(e.created_at)}</small><p>{e.data.notes}</p>{e.observed_change!==null&&<small>Next observed distress change: {e.observed_change>0 && '+'}{e.observed_change} · Temporal association only</small>}</div></div>)}<form onSubmit={e=>{e.preventDefault();act(async()=>{await post('/case-events',{case_id:id,title:event,kind:eventKind,notes:'',active:true});setEvent('');});}}><label>New case event<input value={event} onChange={e=>setEvent(e.target.value)} required minLength={3}/></label><label>Event signal<select value={eventKind} onChange={e=>setEventKind(e.target.value)}>{['general','threat','court_event','compensation_delay','investigation_delay','rehabilitation'].map(v=><option key={v}>{v}</option>)}</select></label><button disabled={busy}>Add event</button></form></section>
 <section className="card"><h2>Schedule follow-up</h2><form onSubmit={e=>{e.preventDefault();act(async()=>{await post('/follow-ups',{case_id:id,assigned_to:assigned,due_at:new Date(due).toISOString(),notes});setDue('');});}}><label>Follow-up date and time<input type="datetime-local" required value={due} onChange={e=>setDue(e.target.value)}/></label><p className="muted">Assigned to {staff.find(s=>s.id===assigned)?.name}. Select a different person above.</p><button disabled={busy}>Schedule follow-up</button></form><label>Contact / outcome note<textarea value={outcome} onChange={e=>setOutcome(e.target.value)} maxLength={1000}/></label>{item.follow_ups.map((f:any)=><div className="list-row" key={f.id}><div>{date(f.due_at)}<small>{f.data.outcome}</small></div><select aria-label={'Follow-up status '+f.id} value={f.status} disabled={busy} onChange={e=>act(async()=>{await patch('/follow-ups/'+f.id,{status:e.target.value,outcome});})}>{['Scheduled','Contacted','Completed','Missed'].map(s=><option key={s}>{s}</option>)}</select></div>)}</section></div>
 <section className="card"><h2>Interventions & observed outcomes</h2>{item.interventions.map((i:any)=><div key={i.id} className="intervention-row"><div><strong>{i.data.kind}</strong><small>{date(i.created_at)}</small><p>{i.data.notes} {i.data.outcome}</p></div><select aria-label={'Intervention status '+i.id} disabled={busy} value={i.status} onChange={e=>act(async()=>{await patch('/interventions/'+i.id,{status:e.target.value,notes:i.data.notes,outcome});})}>{['Assigned','In Progress','Completed','Cancelled'].map(s=><option key={s}>{s}</option>)}</select><div className="outcome">{item.effects.find((f:any)=>f.id===i.id)?.before??'—'} → {item.effects.find((f:any)=>f.id===i.id)?.after.slice(-1)[0]?.score??'Awaiting check-in'}<small>7 days: {item.effects.find((f:any)=>f.id===i.id)?.day_7??'Awaiting data'} · 14 days: {item.effects.find((f:any)=>f.id===i.id)?.day_14??'Awaiting data'}</small><small>{item.effects.find((f:any)=>f.id===i.id)?.note}</small></div></div>)}</section>
 <section className="card"><h2>Support requests</h2>{item.support_requests.length?item.support_requests.map((s:any)=><div className="list-row" key={s.id}><div><strong>{s.data.kind}</strong><p>{s.data.message}</p></div><Badge value={s.status}/></div>):<p className="muted">No support requests yet.</p>}</section></>;
}


