'use client';
import {useEffect,useState} from 'react';
import {Heart,ArrowRight,CheckCircle2,ShieldCheck,CalendarDays,MessageCircle} from 'lucide-react';
import {api,post,date,User} from '../lib/api';
import type {CaseSummary, ChatReply, SupportTimelineItem} from '../lib/types';
import VoiceInput from './VoiceInput';
const kinds=['Counselling','Safety concern','Legal assistance','Financial assistance','Rehabilitation'];
export default function Victim({user,t,language,view,onView,onRefresh,notify,demo}:{user:User;t:Record<string,any>;language:string;view:string;onView:(v:string)=>void;onRefresh:()=>void;notify:(s:string)=>void;demo:boolean}) {
 const [journey,setJourney]=useState<any>(null),[answers,setAnswers]=useState<Record<string,any>>({}),[text,setText]=useState(''),[voice,setVoice]=useState<string|undefined>(),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[wellbeing,setWellbeing]=useState(user.consent?.wellbeing||false),[voiceConsent,setVoiceConsent]=useState(user.consent?.voice||false),[eraseVoice,setEraseVoice]=useState(false),[eraseCheckins,setEraseCheckins]=useState(false),[kind,setKind]=useState(kinds[0]),[message,setMessage]=useState(''),[chat,setChat]=useState(''),[reply,setReply]=useState<ChatReply|null>(null);
 async function refresh(){try{const cases=await api<CaseSummary[]>('/cases');if(cases[0])setJourney(await api('/cases/'+cases[0].id));}catch(e){notify((e as Error).message);}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,20000);return()=>clearInterval(timer);},[]);
 async function action(fn:()=>Promise<void>){setBusy(true);try{await fn();}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
 async function runChatAction(actionItem:{type:string;label:string;kind?:string}){
  if(actionItem.type==='checkin'){onView('checkin');return;}
  if(actionItem.type==='safety_report'){
   await post('/support-requests',{case_id:journey.id,kind:'Safety concern',message:'Safety concern confirmed through guided support'});
   setReply(null);notify(t.received);refresh();return;
  }
  if(actionItem.type==='support_request'){
   await post('/support-requests',{case_id:journey.id,kind:actionItem.kind||'Counselling',message:actionItem.label+' via guided support'});
   setReply(null);notify(t.received);refresh();
  }
 }
 if(view==='privacy'||!user.consent){return <section className="card consent"><div className="icon-block"><ShieldCheck/></div><h1>{t.consentTitle}</h1><p>{t.consentText}</p><label className="check"><input type="checkbox" checked={wellbeing} onChange={e=>{setWellbeing(e.target.checked);if(e.target.checked)setEraseCheckins(false);}}/>{t.agree}</label><label className="check"><input type="checkbox" checked={voiceConsent} onChange={e=>{setVoiceConsent(e.target.checked);if(e.target.checked)setEraseVoice(false);}}/>{t.voiceAgree}</label>{!voiceConsent&&<label className="check"><input type="checkbox" checked={eraseVoice} onChange={e=>setEraseVoice(e.target.checked)}/>Also delete my stored voice recordings now</label>}{!wellbeing&&<label className="check"><input type="checkbox" checked={eraseCheckins} onChange={e=>setEraseCheckins(e.target.checked)}/>Also redact free-text from my past check-ins</label>}<p className="muted">Withdrawal always stops new optional collection. Deletion is optional and irreversible in this prototype.</p><button disabled={busy} onClick={()=>action(async()=>{const saved=await post<any>('/consents',{wellbeing,voice:voiceConsent,language,erase_voice:eraseVoice&&!voiceConsent,erase_checkins:eraseCheckins&&!wellbeing});if(saved?.erasure)notify('Privacy erasure applied.');onRefresh();onView('home');})}>{t.save}</button></section>;}
 if(!journey)return <div className="card">Loading your support journey…</div>;
 if(view==='checkin')return <section className="card checkin"><p className="eyebrow">{t.home}</p><h1>{t.checkin}</h1>{result?<div className="success"><CheckCircle2/><h2>{t.thanks}</h2><p>{t.thanksText}</p><p>{result.assessment_id}</p><button onClick={()=>{setResult(null);onView('journey');}}>{t.journey} <ArrowRight size={16}/></button></div>:<form onSubmit={e=>{e.preventDefault();action(async()=>{setResult(await post('/assessments',{case_id:journey.id,responses:answers,text,language,voice_session_id:voice}));setAnswers({});setText('');setVoice(undefined);refresh();});}}>
  {!user.consent.wellbeing?<div className="notice"><p>{t.agree}</p><button type="button" onClick={()=>onView('privacy')}>{t.privacy}</button></div>:<>
  <div className="form-grid">{['feeling','fear','sleep','daily','avoidance','legal'].map((key,i)=><label key={key}>{i+1}. {t[key]}<select value={answers[key]??''} onChange={e=>setAnswers({...answers,[key]:e.target.value===''?null:Number(e.target.value)})}><option value="">{t.skip}</option>{t.scales.map((label:string,n:number)=><option key={n} value={n}>{label}</option>)}</select></label>)}
  {['threat','safe','support'].map((key,i)=><label key={key}>{i+7}. {t[key]}<select value={answers[key]===undefined||answers[key]===null?'':String(answers[key])} onChange={e=>setAnswers({...answers,[key]:e.target.value===''?null:e.target.value==='true'})}><option value="">{t.skip}</option><option value="true">{t.yes}</option><option value="false">{t.no}</option></select></label>)}
  <label>10. {t.need}<select value={answers.need||''} onChange={e=>setAnswers({...answers,need:e.target.value})}><option value="">{t.skip}</option>{kinds.map((k,i)=><option key={k} value={k}>{t.supportKinds[i]}</option>)}</select></label></div>
  <label>{t.text}<textarea maxLength={10000} rows={5} value={text} onChange={e=>setText(e.target.value)}/></label>
  {user.consent.voice&&<VoiceInput caseId={journey.id} language={language} t={t} onReady={setVoice} onTranscript={setText}/>}
  <button type="submit" disabled={busy}>{busy?'…':t.submit}<ArrowRight size={16}/></button></>}
 </form>}</section>;
 const timeline:SupportTimelineItem[]=Array.isArray(journey.support_timeline)?journey.support_timeline:[];
 return <><div className="page-heading"><div><p className="eyebrow">{journey.id} · {t.home}</p><h1>{view==='journey'?t.journey:t.welcome}</h1><p>{t.subtitle}</p></div><Heart className="heading-icon"/></div>
 {view==='home'&&<div className="welcome-banner"><div><h2>{t.feeling}</h2><p>{t.subtitle}</p><button onClick={()=>onView('checkin')}>{t.checkin}<ArrowRight size={17}/></button></div><div className="care-mark"><Heart size={64} strokeWidth={1}/></div></div>}
 <div className="two-col"><section className="card"><h2>{t.journey}</h2><div className="journey-step"><CheckCircle2/>{t.received}</div><div className="journey-step"><CheckCircle2/>{journey.assigned?t.assigned:'Assignment pending'}</div><div className="journey-step"><CalendarDays/>{journey.follow_ups.length?t.followup:t.none}</div>{journey.interventions.map((i:any)=><div className="list-row" key={i.id}><span>{i.kind}</span><span className="badge">{i.status}</span></div>)}</section><section className="card"><CalendarDays className="accent"/><h2>{t.next}</h2>{journey.follow_ups.filter((f:any)=>f.status==='Scheduled').map((f:any)=><div className="list-row" key={f.id}>{date(f.due_at)}<span className="badge">{f.status}</span></div>)}{!journey.follow_ups.length&&<p>{t.none}</p>}</section></div>
 {(view==='journey'||view==='home')&&<section className="card"><h2>What happened after my check-in</h2><p className="muted">A simple timeline of support actions — without scores or internal notes.</p>{timeline.length?timeline.slice().reverse().slice(0,12).map((item,i)=><div className="timeline-item" key={item.at+item.title+i}><span className="timeline-dot"/><div><strong>{item.title}</strong><small>{date(item.at)}</small>{item.detail&&<p>{item.detail}</p>}</div></div>):<p className="muted">No support activity yet. A check-in or support request will appear here.</p>}</section>}
 <div className="two-col"><section className="card"><h2>{t.supportTitle}</h2><form onSubmit={e=>{e.preventDefault();action(async()=>{await post('/support-requests',{case_id:journey.id,kind,message});setMessage('');notify(t.received);refresh();});}}><select aria-label={t.need} value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map((k,i)=><option key={k} value={k}>{t.supportKinds[i]}</option>)}</select><textarea aria-label={t.text} placeholder={t.text} value={message} onChange={e=>setMessage(e.target.value)} maxLength={3000}/><button disabled={busy}>{t.supportButton}</button></form>{journey.support_requests.map((s:any)=><div className="list-row" key={s.id}><span>{s.kind}</span><span className="badge">{s.status}</span></div>)}</section>
 <section className="card"><h2><MessageCircle size={19}/> {t.chat}</h2><p className="muted">Guided prompts only — not a live counsellor or chatbot.</p><form onSubmit={e=>{e.preventDefault();action(async()=>{setReply(await post<ChatReply>('/chat',{case_id:journey.id,text:chat,language}));setChat('');});}}><textarea aria-label={t.chat} value={chat} onChange={e=>setChat(e.target.value)} maxLength={10000} required/><button disabled={busy||!user.consent?.wellbeing}>{t.send}</button></form>{reply&&<div className="notice"><p>{reply.message}</p>{reply.disclaimer&&<small className="muted">{reply.disclaimer}</small>}{!!reply.resources?.length&&<ul>{reply.resources.map(r=><li key={r.title}><strong>{r.title}</strong> — {r.body}</li>)}</ul>}<div className="button-row">{(reply.actions||[]).map(a=><button key={a.label+a.type} className="secondary" onClick={()=>action(async()=>runChatAction(a))}>{a.label}</button>)}<button className="text-button" onClick={()=>onView('checkin')}>{t.checkin}</button></div></div>}</section></div>
 {demo&&<section className="card"><h2>Demo scenario launcher</h2><p className="muted">Each scenario submits a new synthetic assessment through the risk engine. Consent is required.</p><div className="button-row">{['stable','gradual','threat','critical','improvement'].map(name=><button className="secondary" disabled={busy} key={name} onClick={()=>action(async()=>{await post('/demo/scenario/'+name,{});notify('Scenario saved. The officer queue has been updated.');refresh();})}>{name}</button>)}</div></section>}</>;
}
