'use client';
import {useEffect,useState} from 'react';
import {Activity,Heart,LayoutDashboard,FolderHeart,Bell,CalendarDays,ShieldCheck,LogOut,FlaskConical,ClipboardList,Menu,ArrowRight} from 'lucide-react';
import {api,post,patch,User,date} from '../lib/api';
import Victim from '../components/Victim';
import Authority from '../components/Authority';
import Admin from '../components/Admin';
import en from '../i18n/en.json';import hi from '../i18n/hi.json';import hinglish from '../i18n/hinglish.json';
export default function Home(){
 const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[startupError,setStartupError]=useState(''),[language,setLanguage]=useState('en'),[view,setView]=useState('home'),[email,setEmail]=useState('victim@demo.com'),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[notifications,setNotifications]=useState<any[]>([]),[demo,setDemo]=useState(false),[menu,setMenu]=useState(false);
 const t=({en,hi,hinglish} as any)[language];
 async function refresh(){setStartupError('');try{setUser(await api('/me'));}catch(error){setUser(null);if((error as Error).message!=='Please sign in again')setStartupError((error as Error).message);}finally{setReady(true);}}
 useEffect(()=>{refresh();setLanguage(localStorage.getItem('language')||'en');const expired=()=>{setUser(null);setMessage('Your session expired. Please sign in again.');};window.addEventListener('session-expired',expired);if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(items=>items.forEach(item=>item.unregister())).catch(()=>{});if('caches' in window)caches.keys().then(keys=>keys.filter(key=>key.startsWith('caresignal-')).forEach(key=>caches.delete(key))).catch(()=>{});}return()=>window.removeEventListener('session-expired',expired);},[]);
 useEffect(()=>{localStorage.setItem('language',language);document.documentElement.lang=language==='hi'?'hi':'en';},[language]);
 useEffect(()=>{if(!user)return;const load=()=>api('/notifications').then(setNotifications).catch(()=>{});load();const timer=setInterval(load,20000);return()=>clearInterval(timer);},[user?.id]);
 useEffect(()=>{if(message){const timer=setTimeout(()=>setMessage(''),8000);return()=>clearTimeout(timer);}},[message]);
 const lang=<select aria-label="Language" value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">English</option><option value="hi">हिन्दी</option><option value="hinglish">Hinglish</option></select>;
 const toast=message&&<div className="toast" role="alert">{message}<button aria-label="Dismiss notification" onClick={()=>setMessage('')}>×</button></div>;
 if(!ready)return <div className="loading"><Activity/> Loading CareSignal…</div>;
 if(!user)return <main className="login-page"><section className="login-story"><div className="brand"><span><Activity/></span>CareSignal</div><p className="eyebrow">SIH 26094 · WELLBEING & SUPPORT</p><h1>Behind every case,<br/>there is a person.</h1><p>A continuous view of wellbeing. A clearer path to human support.</p><div className="login-journey"><span>Share</span><i/><span>Understand</span><i/><span>Support</span></div><div className="login-note"><ShieldCheck/><p>AI-assisted insights.<br/>Human-led decisions.</p></div><small>Prototype / Synthetic Data</small></section><section className="login-form"><div className="login-language">{lang}</div><div className="card"><p className="eyebrow">WELCOME TO CARESIGNAL</p><h2>Sign in to your space</h2><p className="muted">Secure access for participants and authorized support teams.</p>{startupError&&<div className="connection-error" role="alert"><span>{startupError}</span><button type="button" className="secondary" onClick={refresh}>Retry connection</button></div>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await post('/auth/login',{email,password});setView('home');await refresh();}catch(err){setMessage((err as Error).message);}finally{setBusy(false);}}}><label>User ID / email<input type="text" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy} type="submit">{busy?'Signing in…':'Sign in'}<ArrowRight size={18}/></button></form><details className="demo-accounts" open><summary>Demo accounts</summary><p>Demo password: <code>Demo@123</code></p><div className="demo-role-grid">{['victim','counsellor','officer','state','national','admin'].map(role=><button className="secondary" key={role} onClick={()=>{setEmail(role+'@demo.com');setPassword('Demo@123');}}>{role}</button>)}</div><small>All accounts and cases are fictional.</small></details></div></section>{toast}</main>;
 const victim=user.role==='victim',aggregate=['state','national'].includes(user.role);
 const navigation=victim?[['home',t.home,Heart],['journey',t.journey,FolderHeart],['privacy',t.privacy,ShieldCheck]]:[['home','Overview',LayoutDashboard],...(!aggregate?[['cases','Case registry',FolderHeart],['alerts','Alerts & review',Bell],['followups','Follow-ups',CalendarDays]]:[]),...(user.role==='admin'?[['users','Users & cases',ShieldCheck],['research','Model research',FlaskConical],['audit','Audit log',ClipboardList]]:[])];
 return <div className="app-shell"><aside className={menu?'sidebar open':'sidebar'}><a href="#main" className="brand"><span><Activity/></span>CareSignal</a><div className="profile"><div className="avatar">{user.name.slice(0,1)}</div><div><strong>{user.name}</strong><small>{user.role==='officer'?'District officer':user.role}</small></div></div><p className="nav-label">WORKSPACE</p><nav>{navigation.map(([key,label,Icon]:any)=><button className={view===key?'nav-item active':'nav-item'} key={key} onClick={()=>{setView(key);setMenu(false);}}><Icon size={19}/>{label}</button>)}<button className={view==='notifications'?'nav-item active':'nav-item'} onClick={()=>setView('notifications')}><Bell size={19}/>Notifications <span className="nav-count">{notifications.filter(n=>!n.read).length}</span></button></nav><div className="sidebar-bottom"><div className="human-note"><ShieldCheck size={18}/><div>Human-led care<small>AI assists. People decide.</small></div></div><button className="nav-item" onClick={async()=>{await post('/auth/logout',{});setUser(null);setNotifications([]);setDemo(false);}}><LogOut size={18}/>{t.logout}</button></div></aside><div className="main-shell"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Open menu" onClick={()=>setMenu(!menu)}><Menu/></button><span className="breadcrumb">CareSignal <span>/</span> {victim?'My support':user.role+' workspace'}</span><div className="button-row"><span className="prototype">Prototype / Synthetic Data</span>{user.demo_enabled&&<label className="demo-toggle"><input type="checkbox" checked={demo} onChange={e=>setDemo(e.target.checked)}/>Demo mode</label>}{lang}</div></header><main id="main" className="content">
 {view==='users'&&user.role==='admin'?<Admin notify={setMessage}/>:view==='notifications'?<section className="card"><h1>Notification center</h1><p className="muted">In-app delivery; email and SMS are simulated.</p>{notifications.map(n=><div className="list-row" key={n.id}><div><strong>{n.data.title}</strong><small>{date(n.created_at)}</small></div>{n.read?<span className="badge">Read</span>:<button className="secondary" onClick={async()=>{await patch('/notifications/'+n.id+'/read',{});setNotifications(await api('/notifications'));}}>Mark read</button>}</div>)}{!notifications.length&&<p className="empty">You’re all caught up.</p>}</section>:victim?<Victim key={user.id} user={user} t={t} language={language} view={view} onView={setView} onRefresh={refresh} notify={setMessage} demo={demo}/>:<Authority key={user.id} user={user} view={view} notify={setMessage}/>}
 <footer>CareSignal · SIH 26094 · Prototype / Synthetic Data <span>Wellbeing monitoring · Not a diagnostic service</span></footer></main></div>{toast}</div>;
}



