"""Optional server-side ASR. Soft-falls back when providers/models are unavailable."""
from __future__ import annotations
import logging
import os
import tempfile
from pathlib import Path

logger = logging.getLogger('caresignal.asr')

def asr_status() -> dict:
    provider = (os.getenv('ASR_PROVIDER') or 'none').lower()
    openai_ready = bool(os.getenv('OPENAI_API_KEY')) and provider in {'openai', 'auto'}
    local_ready = provider in {'local', 'whisper', 'auto'}
    available = openai_ready or (local_ready and _local_whisper_available())
    return {
        'available': available,
        'provider': provider if available else 'none',
        'message': (
            'Server ASR is ready. Review the transcript before submitting.'
            if available else
            'Server ASR is not installed. Use browser speech recognition if available, or type and review your transcript.'
        ),
    }

def _local_whisper_available() -> bool:
    try:
        import whisper  # type: ignore
        return True
    except Exception:
        return False

def transcribe_audio(raw: bytes, language: str = 'en') -> dict:
    status = asr_status()
    if not status['available']:
        return {**status, 'transcript': '', 'confidence': False}
    provider = (os.getenv('ASR_PROVIDER') or 'auto').lower()
    lang = {'en': 'en', 'hi': 'hi', 'hinglish': 'hi'}.get(language, 'en')
    try:
        if provider in {'openai', 'auto'} and os.getenv('OPENAI_API_KEY'):
            text = _openai_whisper(raw, lang)
            return {'available': True, 'provider': 'openai-whisper', 'transcript': text, 'confidence': True,
                    'message': 'Transcript generated by server ASR. Please review before submitting.'}
        if provider in {'local', 'whisper', 'auto'}:
            text = _local_whisper(raw, lang)
            return {'available': True, 'provider': 'local-whisper', 'transcript': text, 'confidence': True,
                    'message': 'Transcript generated by local Whisper. Please review before submitting.'}
    except Exception as exc:
        logger.warning('ASR failed: %s', type(exc).__name__)
        return {'available': False, 'provider': 'none', 'transcript': '', 'ok': False,
                'message': f'Server ASR failed ({type(exc).__name__}). Please type the transcript.'}
    return {**asr_status(), 'transcript': '', 'ok': False}

def _openai_whisper(raw: bytes, language: str) -> str:
    from urllib import request
    import json
    boundary = 'caresignalboundary'
    filename = 'audio.wav'
    body = (
        f'--{boundary}\r\n'
        f'Content-Disposition: form-data; name="model"\r\n\r\nwhisper-1\r\n'
        f'--{boundary}\r\n'
        f'Content-Disposition: form-data; name="language"\r\n\r\n{language}\r\n'
        f'--{boundary}\r\n'
        f'Content-Disposition: form-data; name="file"; filename="{filename}"\r\n'
        f'Content-Type: audio/wav\r\n\r\n'
    ).encode() + raw + f'\r\n--{boundary}--\r\n'.encode()
    req = request.Request(
        'https://api.openai.com/v1/audio/transcriptions',
        data=body,
        headers={
            'Authorization': 'Bearer ' + os.environ['OPENAI_API_KEY'],
            'Content-Type': f'multipart/form-data; boundary={boundary}',
        },
        method='POST',
    )
    with request.urlopen(req, timeout=60) as resp:
        data = json.loads(resp.read().decode())
    return (data.get('text') or '').strip()

def _local_whisper(raw: bytes, language: str) -> str:
    import whisper  # type: ignore
    model_name = os.getenv('WHISPER_MODEL', 'base')
    with tempfile.NamedTemporaryFile(suffix='.wav', delete=False) as tmp:
        tmp.write(raw)
        path = tmp.name
    try:
        model = whisper.load_model(model_name)
        result = model.transcribe(path, language=language if language in {'en', 'hi'} else None)
        return (result.get('text') or '').strip()
    finally:
        Path(path).unlink(missing_ok=True)
